### ISSUE TITLE
react-native run-ios 启动不来 请问是什么问题？

### ISSUE THREAD

**Issue by XJALYN** [NervJS/taro-native-shell#1]
Scanning folders for symlinks in /Users/admin/Desktop/xujie/kmh_taro/taro-native-shell/node_modules (19ms)
Found Xcode project taroDemo.xcodeproj

Could not find iPhone 6 simulator

**Comment by JaneCC** [comment]
I am also this mistake.

**Comment by JaneCC** [comment]
> Scanning folders for symlinks in /Users/admin/Desktop/xujie/kmh_taro/taro-native-shell/node_modules (19ms)
> Found Xcode project taroDemo.xcodeproj
> 
> Could not find iPhone 6 simulator

Give it a try, I solved it.
https://www.jianshu.com/p/a3a351b164ba

**Comment by creasy2010** [comment]
Self test effective!!

**Comment by edenleung** [comment]
it works for me: Xcode `11.3 (11C29)`

## Replace
`/node_modules/react-native/local-cli/runIOS/findMatchingSimulator.js`
- Step 1
```
// Making sure the version of the simulator is an iOS or tvOS (Removes Apple Watch, etc)
if (!version.startsWith('com.apple.CoreSimulator.SimRuntime.iOS') && !version.startsWith('com.apple.CoreSimulator.SimRuntime.tvOS')) {
    continue;
}
```

- Step 2 
```
// Skipping non-available simulator
if (simulator.availability !== '(available)' && simulator.isAvailable !== true) {
    continue;
}
```

## Support Devices
`xcrun simctl list devices | grep iPhone | grep -v unavailable | cut -d'(' -f1`  
```
iPhone 8 
iPhone 8 Plus 
iPhone 11 
iPhone 11 Pro 
iPhone 11 Pro Max
```
`react-native run-ios --simulator="iPhone 11 Pro Max"`
