### ISSUE TITLE
Execution failed for task ':expo-av:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by monakatyking** [NervJS/taro-native-shell#12]
npm install -g @tarojs/cli
taro init myApp
clone taro-native-shell
npm install
执行react-native run-android的时候报错，如下：
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-av:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with
Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:com
mand_line_warnings

**Comment by xiazanzhang** [comment]
壳子的expo-av包版本太低，将expo-av升级到6.0.0在试试

**Comment by Pines-Cheng** [comment]
感谢反馈～
