### ISSUE TITLE
taro init some , 然后直接clone taro-native-shell 没走下来

### ISSUE THREAD

**Issue by evenardo** [NervJS/taro-native-shell#14]
taro init some ， yarn install 了， 然后 yarn dev:rn 也成功了， 8081 那个地址也能访问了。
然后 clone 了 taro-native-shell 下来， 根据官方提示不需要做什么好像， 运行 
react-native run-android
Scanning folders for symlinks in C:\Users\ven\Desktop\taro-native-shell\node_modules (167ms)
JS server already running.
Building and installing the app on the device (cd android && gradlew.bat installDebug)...

> Configure project :app

Installing unimodules:
 unimodules-core@3.0.2 from C:\Users\ven\Desktop\taro-native-shell\node_modules\@unimodules\core
 unimodules-react-native-adapter@3.0.0 from C:\Users\ven\Desktop\taro-native-shell\node_modules\@unimodules\react-native-adapter
 expo-app-loader-provider@6.0.0 from C:\Users\ven\Desktop\taro-native-shell\node_modules\expo-app-loader-provider
 expo-av@6.0.0 from C:\Users\ven\Desktop\taro-native-shell\node_modules\expo-av
 expo-brightness@6.0.0 from C:\Users\ven\Desktop\taro-native-shell\node_modules\expo-brightness
 expo-constants@6.0.0 from C:\Users\ven\Desktop\taro-native-shell\node_modules\expo-constants
 expo-file-system@6.0.2 from C:\Users\ven\Desktop\taro-native-shell\node_modules\expo-file-system
 expo-image-picker@6.0.0 from C:\Users\ven\Desktop\taro-native-shell\node_modules\expo-image-picker
 expo-location@6.0.0 from C:\Users\ven\Desktop\taro-native-shell\node_modules\expo-location
 expo-permissions@6.0.0 from C:\Users\ven\Desktop\taro-native-shell\node_modules\expo-permissions
 expo-sensors@6.0.0 from C:\Users\ven\Desktop\taro-native-shell\node_modules\expo-sensors
 unimodules-barcode-scanner-interface@3.0.0 from C:\Users\ven\Desktop\taro-native-shell\node_modules\unimodules-barcode-scanner-interface
 unimodules-camera-interface@3.0.0 from C:\Users\ven\Desktop\taro-native-shell\node_modules\unimodules-camera-interface
 unimodules-constants-interface@3.0.0 from C:\Users\ven\Desktop\taro-native-shell\node_modules\unimodules-constants-interface
 unimodules-face-detector-interface@3.0.0 from C:\Users\ven\Desktop\taro-native-shell\node_modules\unimodules-face-detector-interface
 unimodules-file-system-interface@3.0.0 from C:\Users\ven\Desktop\taro-native-shell\node_modules\unimodules-file-system-interface
 unimodules-font-interface@3.0.0 from C:\Users\ven\Desktop\taro-native-shell\node_modules\unimodules-font-interface
 unimodules-image-loader-interface@3.0.0 from C:\Users\ven\Desktop\taro-native-shell\node_modules\unimodules-image-loader-interface
 unimodules-permissions-interface@3.0.0 from C:\Users\ven\Desktop\taro-native-shell\node_modules\unimodules-permissions-interface
 unimodules-sensors-interface@3.0.0 from C:\Users\ven\Desktop\taro-native-shell\node_modules\unimodules-sensors-interface
 unimodules-task-manager-interface@3.0.0 from C:\Users\ven\Desktop\taro-native-shell\node_modules\unimodules-task-manager-interface
Observed package id 'extras;intel;Hardware_Accelerated_Execution_Manager' in inconsistent location 'E:\androidSDK\.temp\PackageOperation01'
(Expected 'E:\androidSDK\extras\intel\Hardware_Accelerated_Execution_Manager')

> Task :app:installDebug FAILED
Skipping device 'emulator-5554' (emulator-5554): Device is OFFLINE.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: No online devices found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 44s
405 actionable tasks: 1 executed, 404 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

试了一晚上hello world 没有跑下来，感觉官方的流程都走了，rn 就是不启动，我以为我的模拟器有问题， 然后 react-native init 了一个项目， 确定能跑。 所以希望有人能提供一些解答。

谢谢

**Comment by Chris533** [comment]
升级下expo相关程序包, 参考
```
  "dependencies": {
    "expo-av": "^6.0.0",
    "expo-brightness": "^6.0.0",
    "expo-image-picker": "^6.0.0",
    "expo-location": "^6.0.0",
    "expo-sensors": "^6.0.0",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-canvas": "^0.1.32",
    "react-native-image-crop-picker": "^0.23.1",
    "react-native-image-picker": "^0.28.1",
    "react-native-maps": "^0.25.0",
    "react-native-unimodules": "^0.5.3"
  },
```

**Comment by Chris533** [comment]
用Taro开发RN需要多研究折腾, 维护者的精力花在小程序上, 暂时无解
