### ISSUE TITLE
unable to open file (in target "taroDemoTests" in project "taroDemo")

### ISSUE THREAD

**Issue by BinZhiZhu** [NervJS/taro-native-shell#23]
报错截图

![](http://img.binzhizhu.top/imgs/2020/01/9a1ac1df04f50e35.png)

**Comment by Pines-Cheng** [comment]
![image](https://user-images.githubusercontent.com/9441951/77424766-a24f7280-6e0c-11ea-9032-c8883c371707.png)
你的 RN 版本是 0.60+？

错误提示很详细，RN 0.60+ 会自动 link 原生依赖，如果你手动  link 了，那就 unlink 一下。

**Comment by guhpp** [comment]
我也有相同问题，RN版本是0.59.9

**Comment by ZangTengfei** [comment]
+1

**Comment by purgeyao** [comment]
```

Showing Recent Messages
/Volumes/CodeFile/小程序/ios/taro-native-shell-0.63.2/ios/Pods/Target Support Files/Pods-taroDemo/Pods-taroDemo.debug.xcconfig: unable to open file (in target "taroDemo" in project "taroDemo")


```

**Comment by purgeyao** [comment]
@ZangTengfei @guhpp @BinZhiZhu 解决了么

**Comment by BinZhiZhu** [comment]
> @ZangTengfei @guhpp @BinZhiZhu 解决了么

未解决 ，我在taro-rn-demo 跑 还是会出现同样报错 请问是什么问题？？？@zhiqingchen

**Comment by zhiqingchen** [comment]
用xcode运行试试，然后发下报错

**Comment by BinZhiZhu** [comment]
> 用xcode运行试试，然后发下报错

xcode打开：
![image](https://user-images.githubusercontent.com/35824900/111782575-24755880-88f4-11eb-81a1-70c2ba6b8de4.png)


终端打开：

```
➜  Taro-Mortgage-Calculator git:(master) ✗ react-native run-ios
info Found Xcode workspace "taroDemo.xcworkspace"
info Building (using "xcodebuild -workspace taroDemo.xcworkspace -configuration Debug -scheme taroDemo -destination id=965425FF-ABC6-492C-B456-28CFAC0CF6EA")
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening taroDemo.xcworkspace. Run CLI with --verbose flag for more details.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace taroDemo.xcworkspace -configuration Debug -scheme taroDemo -destination id=965425FF-ABC6-492C-B456-28CFAC0CF6EA

note: Using new build system
note: Building targets in parallel
note: Planning build
note: Using build description from disk
error: /Users/apple/docker/wwwroot/Taro-Mortgage-Calculator/ios/Pods/Target Support Files/Pods-taroDemo/Pods-taroDemo.debug.xcconfig: unable to open file (in target "taroDemo" in project "taroDemo") (in target 'taroDemo' from project 'taroDemo')
error: /Users/apple/docker/wwwroot/Taro-Mortgage-Calculator/ios/Pods/Target Support Files/Pods-taroDemo/Pods-taroDemo.debug.xcconfig: unable to open file (in target "taroDemo" in project "taroDemo") (in target 'taroDemo' from project 'taroDemo')
error: /Users/apple/docker/wwwroot/Taro-Mortgage-Calculator/ios/Pods/Target Support Files/Pods-taroDemo/Pods-taroDemo.debug.xcconfig: unable to open file (in target "taroDemo" in project "taroDemo") (in target 'taroDemo' from project 'taroDemo')
error: /Users/apple/docker/wwwroot/Taro-Mortgage-Calculator/ios/Pods/Target Support Files/Pods-taroDemo/Pods-taroDemo.debug.xcconfig: unable to open file (in target "taroDemo" in project "taroDemo") (in target 'taroDemo' from project 'taroDemo')
warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the taroDemo editor. (in target 'taroDemo' from project 'taroDemo')


** BUILD FAILED **


```

**Comment by BinZhiZhu** [comment]
> 用xcode运行试试，然后发下报错

@zhiqingchen

**Comment by zhiqingchen** [comment]
https://www.jianshu.com/p/3331f60667a4
可以搜一搜类似的问题解决方法

**Comment by BinZhiZhu** [comment]
> https://www.jianshu.com/p/3331f60667a4
> 可以搜一搜类似的问题解决方法

pod install 一直失败,但是我是挂了代理的，这一步一直卡着，有什么好的方法吗?能否失败的依赖单独安装就行了？真的很奇怪，尝试了很多办法，代理也没有问题 @zhiqingchen  大佬，/Users/apple/docker/wwwroot/taro-native-shell/node_modules/react-native/third-party-podspecs/Folly.podspec，这个依赖

```
➜  ios git:(0.59.9) ✗ pod install               
Installing unimodules:
 expo-app-loader-provider@6.0.0 from ../node_modules/expo-app-loader-provider/ios
 expo-av@6.0.0 from ../node_modules/expo-av/ios
 expo-brightness@6.0.0 from ../node_modules/expo-brightness/ios
 expo-constants@6.0.0 from ../node_modules/expo-constants/ios
 expo-file-system@6.0.2 from ../node_modules/expo-file-system/ios
 expo-image-picker@6.0.0 from ../node_modules/expo-image-picker/ios
 expo-location@6.0.0 from ../node_modules/expo-location/ios
 expo-permissions@6.0.0 from ../node_modules/expo-permissions/ios
 expo-sensors@6.0.0 from ../node_modules/expo-sensors/ios
 unimodules-barcode-scanner-interface@3.0.0 from ../node_modules/unimodules-barcode-scanner-interface/ios
 unimodules-camera-interface@3.0.0 from ../node_modules/unimodules-camera-interface/ios
 unimodules-constants-interface@3.0.0 from ../node_modules/unimodules-constants-interface/ios
 unimodules-core@3.0.2 from ../node_modules/@unimodules/core/ios
 unimodules-face-detector-interface@3.0.0 from ../node_modules/unimodules-face-detector-interface/ios
 unimodules-file-system-interface@3.0.0 from ../node_modules/unimodules-file-system-interface/ios
 unimodules-font-interface@3.0.0 from ../node_modules/unimodules-font-interface/ios
 unimodules-image-loader-interface@3.0.0 from ../node_modules/unimodules-image-loader-interface/ios
 unimodules-permissions-interface@3.0.0 from ../node_modules/unimodules-permissions-interface/ios
 unimodules-react-native-adapter@3.0.0 from ../node_modules/@unimodules/react-native-adapter/ios
 unimodules-sensors-interface@3.0.0 from ../node_modules/unimodules-sensors-interface/ios
 unimodules-task-manager-interface@3.0.0 from ../node_modules/unimodules-task-manager-interface/ios

Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Downloading dependencies
Installing DoubleConversion (1.1.6)

Installing EXAV (6.0.0)
Installing EXAppLoaderProvider (6.0.0)
Installing EXBrightness (6.0.0)
Installing EXConstants (6.0.0)
Installing EXFileSystem (6.0.2)
Installing EXImagePicker (6.0.0)
Installing EXLocation (6.0.0)
Installing EXPermissions (6.0.0)
Installing EXSensors (6.0.0)
Installing Folly (2018.10.22.00)

[!] Error installing Folly
[!] /usr/bin/git clone https://github.com/facebook/folly.git /var/folders/bg/dlf3207n7cd02x9c26bg02qm0000gn/T/d20210321-56874-lw9ugx --template= --single-branch --depth 1 --branch v2018.10.22.00

Cloning into '/var/folders/bg/dlf3207n7cd02x9c26bg02qm0000gn/T/d20210321-56874-lw9ugx'...
fatal: unable to access 'https://github.com/facebook/folly.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 
```

**Comment by BinZhiZhu** [comment]
> > https://www.jianshu.com/p/3331f60667a4
> > 可以搜一搜类似的问题解决方法
> 
> pod install 一直失败,但是我是挂了代理的，这一步一直卡着，有什么好的方法吗?能否失败的依赖单独安装就行了？真的很奇怪，尝试了很多办法，代理也没有问题 @zhiqingchen 大佬，/Users/apple/docker/wwwroot/taro-native-shell/node_modules/react-native/third-party-podspecs/Folly.podspec，这个依赖
> 
> ```
> ➜  ios git:(0.59.9) ✗ pod install               
> Installing unimodules:
>  expo-app-loader-provider@6.0.0 from ../node_modules/expo-app-loader-provider/ios
>  expo-av@6.0.0 from ../node_modules/expo-av/ios
>  expo-brightness@6.0.0 from ../node_modules/expo-brightness/ios
>  expo-constants@6.0.0 from ../node_modules/expo-constants/ios
>  expo-file-system@6.0.2 from ../node_modules/expo-file-system/ios
>  expo-image-picker@6.0.0 from ../node_modules/expo-image-picker/ios
>  expo-location@6.0.0 from ../node_modules/expo-location/ios
>  expo-permissions@6.0.0 from ../node_modules/expo-permissions/ios
>  expo-sensors@6.0.0 from ../node_modules/expo-sensors/ios
>  unimodules-barcode-scanner-interface@3.0.0 from ../node_modules/unimodules-barcode-scanner-interface/ios
>  unimodules-camera-interface@3.0.0 from ../node_modules/unimodules-camera-interface/ios
>  unimodules-constants-interface@3.0.0 from ../node_modules/unimodules-constants-interface/ios
>  unimodules-core@3.0.2 from ../node_modules/@unimodules/core/ios
>  unimodules-face-detector-interface@3.0.0 from ../node_modules/unimodules-face-detector-interface/ios
>  unimodules-file-system-interface@3.0.0 from ../node_modules/unimodules-file-system-interface/ios
>  unimodules-font-interface@3.0.0 from ../node_modules/unimodules-font-interface/ios
>  unimodules-image-loader-interface@3.0.0 from ../node_modules/unimodules-image-loader-interface/ios
>  unimodules-permissions-interface@3.0.0 from ../node_modules/unimodules-permissions-interface/ios
>  unimodules-react-native-adapter@3.0.0 from ../node_modules/@unimodules/react-native-adapter/ios
>  unimodules-sensors-interface@3.0.0 from ../node_modules/unimodules-sensors-interface/ios
>  unimodules-task-manager-interface@3.0.0 from ../node_modules/unimodules-task-manager-interface/ios
> 
> Analyzing dependencies
> Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
> Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
> Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
> Downloading dependencies
> Installing DoubleConversion (1.1.6)
> 
> Installing EXAV (6.0.0)
> Installing EXAppLoaderProvider (6.0.0)
> Installing EXBrightness (6.0.0)
> Installing EXConstants (6.0.0)
> Installing EXFileSystem (6.0.2)
> Installing EXImagePicker (6.0.0)
> Installing EXLocation (6.0.0)
> Installing EXPermissions (6.0.0)
> Installing EXSensors (6.0.0)
> Installing Folly (2018.10.22.00)
> 
> [!] Error installing Folly
> [!] /usr/bin/git clone https://github.com/facebook/folly.git /var/folders/bg/dlf3207n7cd02x9c26bg02qm0000gn/T/d20210321-56874-lw9ugx --template= --single-branch --depth 1 --branch v2018.10.22.00
> 
> Cloning into '/var/folders/bg/dlf3207n7cd02x9c26bg02qm0000gn/T/d20210321-56874-lw9ugx'...
> fatal: unable to access 'https://github.com/facebook/folly.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 
> ```

我现在是直接尝试clone 这个壳的分支下来 尝试跑起来

**Comment by BinZhiZhu** [comment]
> > https://www.jianshu.com/p/3331f60667a4
> > 可以搜一搜类似的问题解决方法
> 
> pod install 一直失败,但是我是挂了代理的，这一步一直卡着，有什么好的方法吗?能否失败的依赖单独安装就行了？真的很奇怪，尝试了很多办法，代理也没有问题 @zhiqingchen 大佬，/Users/apple/docker/wwwroot/taro-native-shell/node_modules/react-native/third-party-podspecs/Folly.podspec，这个依赖
> 
> ```
> ➜  ios git:(0.59.9) ✗ pod install               
> Installing unimodules:
>  expo-app-loader-provider@6.0.0 from ../node_modules/expo-app-loader-provider/ios
>  expo-av@6.0.0 from ../node_modules/expo-av/ios
>  expo-brightness@6.0.0 from ../node_modules/expo-brightness/ios
>  expo-constants@6.0.0 from ../node_modules/expo-constants/ios
>  expo-file-system@6.0.2 from ../node_modules/expo-file-system/ios
>  expo-image-picker@6.0.0 from ../node_modules/expo-image-picker/ios
>  expo-location@6.0.0 from ../node_modules/expo-location/ios
>  expo-permissions@6.0.0 from ../node_modules/expo-permissions/ios
>  expo-sensors@6.0.0 from ../node_modules/expo-sensors/ios
>  unimodules-barcode-scanner-interface@3.0.0 from ../node_modules/unimodules-barcode-scanner-interface/ios
>  unimodules-camera-interface@3.0.0 from ../node_modules/unimodules-camera-interface/ios
>  unimodules-constants-interface@3.0.0 from ../node_modules/unimodules-constants-interface/ios
>  unimodules-core@3.0.2 from ../node_modules/@unimodules/core/ios
>  unimodules-face-detector-interface@3.0.0 from ../node_modules/unimodules-face-detector-interface/ios
>  unimodules-file-system-interface@3.0.0 from ../node_modules/unimodules-file-system-interface/ios
>  unimodules-font-interface@3.0.0 from ../node_modules/unimodules-font-interface/ios
>  unimodules-image-loader-interface@3.0.0 from ../node_modules/unimodules-image-loader-interface/ios
>  unimodules-permissions-interface@3.0.0 from ../node_modules/unimodules-permissions-interface/ios
>  unimodules-react-native-adapter@3.0.0 from ../node_modules/@unimodules/react-native-adapter/ios
>  unimodules-sensors-interface@3.0.0 from ../node_modules/unimodules-sensors-interface/ios
>  unimodules-task-manager-interface@3.0.0 from ../node_modules/unimodules-task-manager-interface/ios
> 
> Analyzing dependencies
> Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
> Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
> Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
> Downloading dependencies
> Installing DoubleConversion (1.1.6)
> 
> Installing EXAV (6.0.0)
> Installing EXAppLoaderProvider (6.0.0)
> Installing EXBrightness (6.0.0)
> Installing EXConstants (6.0.0)
> Installing EXFileSystem (6.0.2)
> Installing EXImagePicker (6.0.0)
> Installing EXLocation (6.0.0)
> Installing EXPermissions (6.0.0)
> Installing EXSensors (6.0.0)
> Installing Folly (2018.10.22.00)
> 
> [!] Error installing Folly
> [!] /usr/bin/git clone https://github.com/facebook/folly.git /var/folders/bg/dlf3207n7cd02x9c26bg02qm0000gn/T/d20210321-56874-lw9ugx --template= --single-branch --depth 1 --branch v2018.10.22.00
> 
> Cloning into '/var/folders/bg/dlf3207n7cd02x9c26bg02qm0000gn/T/d20210321-56874-lw9ugx'...
> fatal: unable to access 'https://github.com/facebook/folly.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 
> ```

我一直重复着 pod install 。。看看能否顺利安装好Podfile这些依赖  = =

**Comment by BinZhiZhu** [comment]
> https://www.jianshu.com/p/3331f60667a4
> 可以搜一搜类似的问题解决方法

我在0.59版本那个分支是可以成功run 起来，但是我切到0.63.2版本的分支，重新安装依赖以及pod install ，这个过程也是成功的，然后我run-ios，又是跑不起来：

```
fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
1 error generated.
fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
1 error generated.
fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
1 error generated.
fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
1 error generated.
3 errors generated.
6 errors generated.
fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
1 error generated.
fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
1 error generated.
fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
1 error generated.
10 errors generated.
fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
1 error generated.
fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
1 error generated.
fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
1 error generated.
fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
1 error generated.
fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
1 error generated.
5 errors generated.
fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
1 error generated.
fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
1 error generated.
2 errors generated.
fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
1 error generated.
fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
1 error generated.
22 errors generated.
23 errors generated.
```

![image](https://user-images.githubusercontent.com/35824900/111895828-2eac6980-8a50-11eb-83ea-a4a532031933.png)


我真的太难了 。。 @zhiqingchen  这些是什么问题呢，切个分支重新跑一次又是失败了

**Comment by BinZhiZhu** [comment]
> > https://www.jianshu.com/p/3331f60667a4
> > 可以搜一搜类似的问题解决方法
> 
> 我在0.59版本那个分支是可以成功run 起来，但是我切到0.63.2版本的分支，重新安装依赖以及pod install ，这个过程也是成功的，然后我run-ios，又是跑不起来：
> 
> ```
> fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
> fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
> fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
> fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
> fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
> 1 error generated.
> fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
> 1 error generated.
> fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
> fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
> 1 error generated.
> fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
> 1 error generated.
> 3 errors generated.
> 6 errors generated.
> fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
> 1 error generated.
> fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
> 1 error generated.
> fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
> 1 error generated.
> 10 errors generated.
> fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
> 1 error generated.
> fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
> fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
> 1 error generated.
> fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
> 1 error generated.
> fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
> 1 error generated.
> fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
> 1 error generated.
> 5 errors generated.
> fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
> 1 error generated.
> fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
> fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
> 1 error generated.
> 2 errors generated.
> fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
> 1 error generated.
> fatal error: module map file '/Users/apple/Library/Developer/Xcode/DerivedData/taroDemo-gasbynoyyufdqxceqrxcjjjgrafa/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
> 1 error generated.
> 22 errors generated.
> 23 errors generated.
> ```
> 
> ![image](https://user-images.githubusercontent.com/35824900/111895828-2eac6980-8a50-11eb-83ea-a4a532031933.png)
> 
> 我真的太难了 。。 @zhiqingchen 这些是什么问题呢，切个分支重新跑一次又是失败了

@Pines-Cheng

**Comment by BinZhiZhu** [comment]
![image](https://user-images.githubusercontent.com/35824900/111896985-4c7dcc80-8a58-11eb-88fb-cfe3fea4a353.png)

成功跑起来了 = =

**Comment by BinZhiZhu** [comment]
https://taro-docs.jd.com/taro/docs/react-native

文档没有更新，我觉得文档应该更加详细一些，例如如果RN版本是最新的分支0.63.2,那么构建js bundle应该是访问：

http://localhost:8081/index.bundle?platform=ios&dev=true

文档写着是：http://localhost:8081/rn_temp/index.bundle?platform=ios&dev=true 等这些不够完善

**Comment by zhiqingchen** [comment]
> https://taro-docs.jd.com/taro/docs/react-native
> 
> 
> 
> 文档没有更新，我觉得文档应该更加详细一些，例如如果RN版本是最新的分支0.63.2,那么构建js bundle应该是访问：
> 
> 
> 
> http://localhost:8081/index.bundle?platform=ios&dev=true
> 
> 
> 
> 文档写着是：http://localhost:8081/rn_temp/index.bundle?platform=ios&dev=true 等这些不够完善
> 
> 

文档已修复
