### ISSUE TITLE
直接clone下来的项目通不过编译

### ISSUE THREAD

**Issue by wsxiaoluob** [NervJS/taro-native-shell#3]
环境：
react-native-cli: 2.0.1
react-native: 0.59.9
react-native run-ios 报错信息如下：
The following build commands failed:
	CompileC /Users/Xiaoluob/Desktop/taro-native-shell-master/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/third-party.build/Objects-normal/x86_64/vlog_is_on.o /Users/Xiaoluob/Desktop/taro-native-shell-master/node_modules/react-native/third-party/glog-0.3.4/src/vlog_is_on.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/taroDemo.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/taroDemo.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
是否是react-native的版本问题？

**Comment by zhangzhenfei** [comment]
请问怎么解决的，我这边也遇到这个问题了

**Comment by Vidtion** [comment]
一样

**Comment by zouyang2015** [comment]
有解决吗？什么情况？
