### ISSUE TITLE
gradle镜像怎么设置

### ISSUE THREAD

**Issue by taoqf** [NervJS/taro-native-shell#35]
我发现在当前项目下设置镜像不起使用（话说这东西应该在这项目中设好镜像呀）。我本想提pr的，但这块我不太熟悉。我发现只是在当前项目下添加镜像不起使用，我修改了`node_modules/expo-av/android/build.gradle`才起使用。有谁能处理一下吗？直接使用咱们这个项目会超时。几次都失败，不仅仅是时间长的问题。
另外，也不是每个人都要有梯子吧。没有梯子这东西就没法用了，我花了几个小时找问题，才设置好的镜像。

**Comment by zhiqingchen** [comment]
有意识到这个问题了，后续优先解决。

**Comment by zhiqingchen** [comment]
https://github.com/NervJS/taro-native-shell/pull/36
