### ISSUE TITLE
Invariant Violation: "taroDemo" has not been registered.

### ISSUE THREAD

**Issue by Zhoukaiqiang** [NervJS/taro-native-shell#44]
我还完全不了解RN，我在taro项目中运行 `taro build --type rn --platform android`，然后shell中运行 `react-native run-android`，报如标题的错。
修改配置文件config/index.js的rn.appName = taroDemo。其他是cli初始化的东西，除了src/目录以外
依赖如下：
`"dependencies": {
    "@babel/runtime": "^7.7.7",
    "@reduxjs/toolkit": "^1.5.1",
    "@tarojs/cli": "3.2.8",
    "@tarojs/components": "3.2.8",
    "@tarojs/react": "3.2.8",
    "@tarojs/rn-runner": "^3.2.8",
    "@tarojs/runtime": "3.2.8",
    "@tarojs/taro": "3.2.8",
    "@tarojs/taro-rn": "^3.2.8",
    "lodash": "^4.17.15",
    "react": "^17.0.0",
    "react-dom": "^17.0.0",
    "react-native": "^0.64.0",
    "react-redux": "^7.2.3",
    "redux": "^4.0.5",
    "taro-ui": "^3.0.0-alpha.10"
}`

**Comment by zhiqingchen** [comment]
`yarn dev:rn --reset-cache`
