### ISSUE TITLE
yarn ios报错

### ISSUE THREAD

**Issue by luckyGTL** [NervJS/taro-native-shell#58]
![middle_img_v2_7849fb82-ed22-4aa3-be5c-f31d4c72c72g](https://user-images.githubusercontent.com/31212280/143417159-2d55301e-5176-41f4-83ec-0ecdaeb2b46c.png)

**Comment by luckyGTL** [comment]
用xcode看了下具体报错

![image](https://user-images.githubusercontent.com/31212280/143425061-4f4b5aa4-7e7c-4f4f-af19-dd7ac443c3fa.png)

**Comment by zhiqingchen** [comment]
"expo-keep-awake": "~9.2.0",

**Comment by luckyGTL** [comment]
> "expo-keep-awake": "~9.2.0",

 "expo-keep-awake": "^9.2.0",本地是这个

**Comment by luckyGTL** [comment]
> "expo-keep-awake": "~9.2.0",

 "expo-keep-awake": "^9.2.0",本地是这个

**Comment by zhiqingchen** [comment]
0.66 已修复
https://github.com/NervJS/taro-native-shell/commit/1d5f9f5b27b1bbbdc2ad5ddac54c81f9c37bbca5

**Comment by zhiqingchen** [comment]
依赖有不一致，可执行
```
yarn upgradePeerdeps
```

对依赖进行同步

可修改script指定对应的taro 版本，默认为最新版

**Comment by zhiqingchen** [comment]
https://github.com/NervJS/taro-native-shell/commit/fdb78a23e1572d654e9294a7a43fc5162d379d61

0.64 已修复

**Comment by luckyGTL** [comment]
> 0.66 已修复 [1d5f9f5](https://github.com/NervJS/taro-native-shell/commit/1d5f9f5b27b1bbbdc2ad5ddac54c81f9c37bbca5)
用你最新提交的，0.66分支。还是有报错
![middle_img_v2_e148d36a-0d48-4df1-b886-19bce18713ag](https://user-images.githubusercontent.com/31212280/143439342-5da94536-915d-4ede-b678-dc0c0a88504f.png)

**Comment by luckyGTL** [comment]
> 0.66 已修复 [1d5f9f5](https://github.com/NervJS/taro-native-shell/commit/1d5f9f5b27b1bbbdc2ad5ddac54c81f9c37bbca5)

用你最新提交的，0.66分支。还是有报错
![image](https://user-images.githubusercontent.com/31212280/143439526-b188c049-13a8-4e02-80b2-0123db424406.png)

**Comment by luckyGTL** [comment]
> > 0.66 已修复 [1d5f9f5](https://github.com/NervJS/taro-native-shell/commit/1d5f9f5b27b1bbbdc2ad5ddac54c81f9c37bbca5)
> 
> 用你最新提交的，0.66分支。还是有报错 ![image](https://user-images.githubusercontent.com/31212280/143439526-b188c049-13a8-4e02-80b2-0123db424406.png)

重新执行了 pod install 空壳子启动了，但是报错了
![middle_img_v2_566f837b-56a3-4989-8577-86ea75944f3g](https://user-images.githubusercontent.com/31212280/143447489-8cbf2ee4-f646-40df-98bc-ce956481fc58.png)

**Comment by zhiqingchen** [comment]
https://docs.taro.zone/blog/2021-10-14-Taro-React-Native-update

看下文档，需要build

**Comment by luckyGTL** [comment]
> https://docs.taro.zone/blog/2021-10-14-Taro-React-Native-update
> 
> 看下文档，需要build

不是执行这个吗
![image](https://user-images.githubusercontent.com/31212280/143515035-40d98db4-3390-4295-bd09-548a3919ee44.png)

**Comment by zhiqingchen** [comment]
yarn build:rn --platform ios
