### ISSUE TITLE
_reactNative.UIManager.getViewManagerConfig is not a function

### ISSUE THREAD

**Issue by Pines-Cheng** [NervJS/taro-native-shell#6]
expo-av 的问题，已经提了 PR ，等发版。
https://github.com/expo/expo/issues/4737

着急的也可以自行 fix : https://github.com/expo/expo/commit/27f4c75d0b88cded2f7b109519ad70f58c0d4ad4

**Comment by aijle** [comment]
"resolutions": {
        "react-native-unimodules": "0.5.2",
        "expo-av": "^6.0.0",
        "expo-brightness": "^6.0.0",
        "expo-file-system": "^6.0.0",
        "expo-image-picker": "^6.0.0",
        "expo-keep-awake": "^6.0.0",
        "expo-location": "^6.0.0",
        "expo-sensors": "^6.0.0"
    }

**Comment by tourze** [comment]
> "resolutions": {
> "react-native-unimodules": "0.5.2",
> "expo-av": "^6.0.0",
> "expo-brightness": "^6.0.0",
> "expo-file-system": "^6.0.0",
> "expo-image-picker": "^6.0.0",
> "expo-keep-awake": "^6.0.0",
> "expo-location": "^6.0.0",
> "expo-sensors": "^6.0.0"
> }

yarn才有效，npm无效。。。
@Pines-Cheng 能不能在taro的包那里更新下expo版本？
