### ISSUE TITLE
yarn android 报错

### ISSUE THREAD

**Issue by luckyGTL** [NervJS/taro-native-shell#60]
1.拉去0.66分支；
2.yarn install安装依赖
3.yarn android报错；
报错信息：
* What went wrong:
A problem occurred configuring project ':react-native-community_cameraroll'.
> Could not resolve all artifacts for configuration ':react-native-community_cameraroll:classpath'.
   > Could not download builder-3.2.1.jar (com.android.tools.build:builder:3.2.1)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.2.1/builder-3.2.1.jar'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.2.1/builder-3.2.1.jar'.
            > Connect to dl.google.com:443 [dl.google.com/127.0.1.2] failed: Connection refused: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 40s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-community_cameraroll'.
> Could not resolve all artifacts for configuration ':react-native-community_cameraroll:classpath'.
   > Could not download builder-3.2.1.jar (com.android.tools.build:builder:3.2.1)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.2.1/builder-3.2.1.jar'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.2.1/builder-3.2.1.jar'.
            > Connect to dl.google.com:443 [dl.google.com/127.0.1.2] failed: Connection refused: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 40s

    at makeError (F:\H5\taro-native-shell\node_modules\execa\index.js:174:9)
    at F:\H5\taro-native-shell\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runOnAllDevices (F:\H5\taro-native-shell\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:106:5)
    at async Command.handleAction (F:\H5\taro-native-shell\node_modules\@react-native-community\cli\build\index.js:186:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by 4332weizi** [comment]
在某些网络下，访问dl.google.com可能需要梯子，麻烦用梯子重试下

**Comment by luckyGTL** [comment]
> 在某些网络下，访问dl.google.com可能需要梯子，麻烦用梯子重试下

用了梯子，执行还是失败

**Comment by 4332weizi** [comment]
你的dl.google.com为什么会被解析到127.0.1.2呢

**Comment by luckyGTL** [comment]
> 你的dl.google.com为什么会被解析到127.0.1.2呢

不知道啊 我百度看看

**Comment by luckyGTL** [comment]
> 你的dl.google.com为什么会被解析到127.0.1.2呢

正常情况是解析到哪里

**Comment by 4332weizi** [comment]
如果代理配置没问题仍然报错的话，可以在`./node_modules/@react-native-community/cameraroll/android/build.gradle`中添加阿里云的Google Maven代理仓。
```
repositories {
    maven { url 'https://maven.aliyun.com/repository/google' }
    google()
    jcenter()
 }
```
