### ISSUE TITLE
android打包apk报错

### ISSUE THREAD

**Issue by luckyGTL** [NervJS/taro-native-shell#61]
![image](https://user-images.githubusercontent.com/31212280/145185904-e7030b58-865b-4b0e-8142-9bccca9357d6.png)

**Comment by zhiqingchen** [comment]
依赖包不存在，检查网络情况

**Comment by zhiqingchen** [comment]
或使用国内代理

**Comment by zhiqingchen** [comment]
https://github.com/NervJS/taro-native-shell/issues/60#issuecomment-983333874

**Comment by luckyGTL** [comment]
> 依赖包不存在，检查网络情况

OK 我试试

**Comment by luckyGTL** [comment]
我电脑配置问题。试了同事电脑都没问题。
