### ISSUE TITLE
0.67-expo yarn android错误。

### ISSUE THREAD

**Issue by LSNXUV** [NervJS/taro-native-shell#77]
### **我把taro-native-shell放在TaroRN项目里面的，不知道有没有影响**

PS C:\Users\Supernova\Desktop\TaroRN-0.67\TaroRN\taro-native-shell> yarn android

yarn run v1.22.17
warning ..\..\..\..\package.json: No license field
$ react-native run-android
warn Package expo-modules-core has been ignored because it contains invalid configuration. Reason: "dependency.platforms.ios" must be of type object        
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1640 file(s) to forward-jetify. Using 16 workers...
info JS server already running.
info Installing the app...

> Configure project :app
WARNING:DSL element 'dexOptions' is obsolete and should be removed.
It will be removed in version 8.0 of the Android Gradle plugin.
Using it has no effect, and the AndroidGradle plugin optimizes dexing automatically.
task ':app:processDebugManifest'

> Configure project :expo-application
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-av
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-barcode-scanner
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-brightness
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-camera
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-constants
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-file-system
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-font
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-image-loader
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-image-picker
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-keep-awake
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-location
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-modules-core
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-sensors
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo

Using expo modules
  - expo-application (4.2.2)
  - expo-av (11.2.3)
  - expo-barcode-scanner (11.4.0)
  - expo-brightness (10.3.0)
  - expo-camera (12.3.0)
  - expo-constants (13.2.3)
  - expo-file-system (14.1.0)
  - expo-font (10.2.0)
  - expo-image-loader (3.2.0)
  - expo-image-picker (13.1.1)
  - expo-keep-awake (10.2.0)
  - expo-location (14.3.0)
  - expo-modules-core (0.11.3)
  - expo-sensors (11.4.0)

WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.
WARNING:The specified Android SDK Build Tools version (28.0.3) is ignored, as 
it is below the minimum supported version (30.0.3) for Android Gradle Plugin 7.1.2.
Android SDK Build Tools 30.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '28.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
WARNING:The specified Android SDK Build Tools version (30.0.2) is ignored, as 
it is below the minimum supported version (30.0.3) for Android Gradle Plugin 7.1.2.
Android SDK Build Tools 30.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '30.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :expo:compileDebugKotlin FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings
341 actionable tasks: 3 executed, 338 up-to-date
(node:3164) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\Users\Supernova\Desktop\TaroRN-0.67\TaroRN\taro-native-shell\node_modules\@expo\devcert\node_modules\tslib\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)    
(node:6424) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\Users\Supernova\Desktop\TaroRN-0.67\TaroRN\taro-native-shell\node_modules\@expo\devcert\node_modules\tslib\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)    
e: C:\Users\Supernova\Desktop\TaroRN-0.67\TaroRN\taro-native-shell\node_modules\expo\android\src\main\java\expo\modules\ReactActivityDelegateWrapper.kt: (13, 27): Unresolved reference: ReactInstanceEventListener
e: C:\Users\Supernova\Desktop\TaroRN-0.67\TaroRN\taro-native-shell\node_modules\expo\android\src\main\java\expo\modules\ReactActivityDelegateWrapper.kt: (161, 43): Unresolved reference: ReactInstanceEventListener
e: C:\Users\Supernova\Desktop\TaroRN-0.67\TaroRN\taro-native-shell\node_modules\expo\android\src\main\java\expo\modules\ReactActivityDelegateWrapper.kt: (162, 9): 'onReactContextInitialized' overrides nothing
e: C:\Users\Supernova\Desktop\TaroRN-0.67\TaroRN\taro-native-shell\node_modules\expo\android\src\main\java\expo\modules\ReactActivityDelegateWrapper.kt: (163, 74): Type mismatch: inferred type is <no name provided> but ReactInstanceManager.ReactInstanceEventListener! was expected
e: C:\Users\Supernova\Desktop\TaroRN-0.67\TaroRN\taro-native-shell\node_modules\expo\android\src\main\java\expo\modules\ReactActivityDelegateWrapper.kt: (167, 74): Type mismatch: inferred type is <no name provided> but ReactInstanceManager.ReactInstanceEventListener! was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
(node:3164) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\Users\Supernova\Desktop\TaroRN-0.67\TaroRN\taro-native-shell\node_modules\@expo\devcert\node_modules\tslib\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)    
(node:6424) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\Users\Supernova\Desktop\TaroRN-0.67\TaroRN\taro-native-shell\node_modules\@expo\devcert\node_modules\tslib\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)    
e: C:\Users\Supernova\Desktop\TaroRN-0.67\TaroRN\taro-native-shell\node_modules\expo\android\src\main\java\expo\modules\ReactActivityDelegateWrapper.kt: (13, 27): Unresolved reference: ReactInstanceEventListener
e: C:\Users\Supernova\Desktop\TaroRN-0.67\TaroRN\taro-native-shell\node_modules\expo\android\src\main\java\expo\modules\ReactActivityDelegateWrapper.kt: (161, 43): Unresolved reference: ReactInstanceEventListener
e: C:\Users\Supernova\Desktop\TaroRN-0.67\TaroRN\taro-native-shell\node_modules\expo\android\src\main\java\expo\modules\ReactActivityDelegateWrapper.kt: (162, 9): 'onReactContextInitialized' overrides nothing
e: C:\Users\Supernova\Desktop\TaroRN-0.67\TaroRN\taro-native-shell\node_modules\expo\android\src\main\java\expo\modules\ReactActivityDelegateWrapper.kt: (163, 74): Type mismatch: inferred type is <no name provided> but ReactInstanceManager.ReactInstanceEventListener! was expected
e: C:\Users\Supernova\Desktop\TaroRN-0.67\TaroRN\taro-native-shell\node_modules\expo\android\src\main\java\expo\modules\ReactActivityDelegateWrapper.kt: (167, 74): Type mismatch: inferred type is <no name provided> but ReactInstanceManager.ReactInstanceEventListener! was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s

    at makeError (C:\Users\Supernova\Desktop\TaroRN-0.67\TaroRN\taro-native-shell\node_modules\execa\index.js:174:9)
    at C:\Users\Supernova\Desktop\TaroRN-0.67\TaroRN\taro-native-shell\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)     
    at async runOnAllDevices (C:\Users\Supernova\Desktop\TaroRN-0.67\TaroRN\taro-native-shell\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\Users\Supernova\Desktop\TaroRN-0.67\TaroRN\taro-native-shell\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by zhiqingchen** [comment]
> 把taro-native-shell放在TaroRN项目里面的

两者需要结合的话，建议 `taro init` 选择 `react-native`

**Comment by LSuperNova** [comment]
> 

我想同时生成微信小程序，默认模板才行吧😭

**Comment by LSuperNova** [comment]
> 

我想同时生成微信小程序，默认模板才行吧😭

**Comment by LSNXUV** [comment]
@zhiqingchen  我想同时生成微信小程序，默认模板才行吧😭，我想问下taro-native-shell应该放在哪里呢，是放在taro项目内部还是跟它同级啊。

**Comment by zhiqingchen** [comment]
> > 把taro-native-shell放在TaroRN项目里面的
> 
> 两者需要结合的话，建议 `taro init` 选择 `react-native`

建议 taro init 选择 react-native，这个支持小程序的，参考 https://github.com/wuba/taro-playground 项目

**Comment by LSNXUV** [comment]
> > 把taro-native-shell放在TaroRN项目里面的
> 
> 两者需要结合的话，建议 `taro init` 选择 `react-native`
