### ISSUE TITLE
This version of Xcode does not support building or migrating Swift 3.x target

### ISSUE THREAD

**Issue by lys623** [NervJS/taro-native-shell#79]
![image](https://user-images.githubusercontent.com/4364314/188260149-f6094153-91c9-458d-9973-90f88becb310.png)

求解怎么处理？
xcode 版本：12.3
taro-native-shell分支：0.68.0

**Comment by zhiqingchen** [comment]
taroDemoTests可以删掉，或直接点击 OK

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1876158/188315463-959be564-8f02-4027-abff-af2e3ea1bfb5.png">

**Comment by lys623** [comment]
> taroDemoTests可以删掉，或直接点击 OK
> 
> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/1876158/188315463-959be564-8f02-4027-abff-af2e3ea1bfb5.png">

还是不行，一堆报错
![image](https://user-images.githubusercontent.com/4364314/188353008-dcbc56d8-3c99-430b-8cf8-536860756378.png)

**Comment by zhiqingchen** [comment]
xcode建议升级到最新版本

**Comment by zhiqingchen** [comment]
try

https://github.com/NervJS/taro-native-shell/commit/6834490668ce3e31488cb8361b4bb4460d98ca58
