### ISSUE TITLE
这些commit在哪里？

### ISSUE THREAD

**Issue by duanju** [NervJS/taro-native-shell#86]
修改部分代码以支持 Taro，此部分可以直接 cherry-pick

[scripts] 修改 android, ios 脚本，增加 upgradePeerdeps 脚本
[devDependencies] 增加 install-peerdeps 和 pod-install
[ios] 添加相关 APP 权限说明
[ios] 使用亮色主题
[android] 添加国内 maven 源
[android] 添加 gif 支持
[android] 注释原 react native 打包
[android] 使用亮色主题
[docs] 复制该 README.md 文件
[license] 复制 LICENSE 文件

**Comment by zhiqingchen** [comment]
https://github.com/NervJS/taro-native-shell/commit/9d9b2009b4128f4b44a7c3fd4faca0f82a3144a4

**Comment by zhiqingchen** [comment]
类似上面的，不同版本都会有这样的commit
