### ISSUE TITLE
发布到Google Play时发现错误，异常信息为 UnsatisfiedLinkError: dlopen failed: “/data/data/{package}/lib-main/libgnustl_shared.so” is 32-bit instead of 64-bit。

### ISSUE THREAD

**Issue by farisong** [NervJS/taro-native-shell#9]
发布到Google Play时发现错误，异常信息为：
`UnsatisfiedLinkError: dlopen failed: “/data/data/{package}/lib-main/libgnustl_shared.so” is 32-bit instead of 64-bit`

解决方案，按照下面内容修改gradle文件，
```
ndk {
   abiFilters "armeabi-v7a", "x86", 'x86_64'
}
```

**Comment by Pines-Cheng** [comment]
感谢反馈～

**Comment by 347649749xzh** [comment]
Will your react-native
What is the version?

**Comment by 347649749xzh** [comment]
请问你的react-native
版本是多少？

**Comment by farisong** [comment]
FYI, 0.55.
