### ISSUE TITLE
版本更新

### ISSUE THREAD

**Issue by isnolan** [NervJS/taro-native-shell#91]
是否有计划升级至React Native 0.72 ？

**Comment by zhiqingchen** [comment]
0.71 在 taro 3.7 可用

0.72 目前方案上有问题，会等 0.73

**Comment by isnolan** [comment]
- [尝试集成模式初始化v3.7模版失败](https://github.com/NervJS/taro-project-templates/issues/110)
- 尝试分离模式初始化v0.71.0构建失败
```
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/yhostc/Library/Developer/Xcode/DerivedData/taroDemo-bmsgrimarmbokvfdgteogendavqz/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-webview.build/Objects-normal/arm64/RNCWKProcessPoolManager.o /Users/yhostc/Project/taro/taro-native-shell/node_modules/react-native-webview/apple/RNCWKProcessPoolManager.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-webview' from project 'Pods')
(1 failure)
```
目前我们在评估是直接使用Expo，还是直接使用Taro. 前者意味着放弃Taro集成框架的优势能力以及打包到多种小程序的能力。而后者意味着放弃很多原生能力。

比如，我们想要集成oauth2.0的能力，国内社群似乎在这方面很少涉猎，尽管我们找到了google sign in项目实现了。但优雅不足，还是希望接入[react-native-app-auth](https://github.com/FormidableLabs/react-native-app-auth)这样的组件，更富通用性，而这个组件接入Taro v0.70版本是困难的，或者说我尚未探索到方法。

所以期望有一种方式，就是可以在原生React Native 或 Expo项目中直接接入和引用Taro，实现两者优势互补。

**Comment by isnolan** [comment]
@zhiqingchen 是否有资料说明Taro基于Expo都做了哪些工作？

**Comment by zhiqingchen** [comment]
https://github.com/NervJS/taro-native-shell#%E8%AF%A5%E4%BB%93%E5%BA%93%E5%A6%82%E4%BD%95%E7%94%9F%E6%88%90

**Comment by zhiqingchen** [comment]
https://github.com/NervJS/taro-native-shell/tree/0.73.0


0.73 支持将与 4.0 一起发布
