### ISSUE TITLE
能否在后续版本中针对iOS减少其它框架的依赖，特别是expo

### ISSUE THREAD

**Issue by zhhwdev** [NervJS/taro-native-shell#93]
因为我们的app中本来已经集成好了rn的环境，不太想引入太多的原生依赖了。

**Comment by zhiqingchen** [comment]
如只用到基础的，可以不集成 expo，不影响打包。
例如不使用二维码扫描，可以不集成 expo-barcode-scanner。

参考：
https://github.com/NervJS/taro-native-shell/tree/0.68.0?tab=readme-ov-file#%E9%99%84taro-%E5%8E%9F%E7%94%9F%E4%BE%9D%E8%B5%96%E6%98%8E%E7%BB%86%E8%A1%A8

**Comment by zhiqingchen** [comment]
后续仍会继续依赖 Expo，因为小程序功能很多，很多功能都需要原生依赖，RN 本身并不支持。
