### ISSUE TITLE
Android 打包前异常，错误： the argument to replace_text() must be a String

### ISSUE THREAD

**Issue by Dssssds** [NervJS/taro-native-shell#94]
## 具体错误如下

···
shuaidongs-MacBook-Pro:taroshell ds$ cd android && bundle update && bundle exec fastlane assemble

Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Using rake 13.1.0 (was 13.0.6)
Fetching aws-partitions 1.875.0 (was 1.587.0)
Using jmespath 1.6.2 (was 1.6.1)
Using bundler 2.3.5
Using artifactory 3.0.15
Using atomos 0.1.3
Using aws-eventstream 1.3.0 (was 1.2.0)
Using colored2 3.1.2
Using rexml 3.2.6 (was 3.2.5)
Using public_suffix 5.0.4 (was 4.0.7)
Using claide 1.1.0
Using colored 1.2
Using emoji_regex 3.2.3
Using excon 0.108.0 (was 0.92.3)
Using faraday-em_http 1.0.0
Using faraday-em_synchrony 1.0.0
Using dotenv 2.8.1 (was 2.7.6)
Using babosa 1.0.4
Using faraday-httpclient 1.0.1
Using highline 2.0.3
Using declarative 0.0.20
Using faraday-net_http_persistent 1.2.0
Using domain_name 0.6.20231109 (was 0.5.20190701)
Using faraday-excon 1.1.0
Using faraday-retry 1.0.3
Using faraday-net_http 1.0.1
Using digest-crc 0.6.5 (was 0.6.4)
Using faraday-patron 1.0.0
Using faraday-rack 1.0.0
Using multipart-post 2.3.0 (was 2.0.0)
Using ruby2_keywords 0.0.5
Using fastimage 2.3.0 (was 2.2.6)
Using gh_inspector 1.1.3
Using jwt 2.7.1 (was 2.3.0)
Using multi_json 1.15.0
Using os 1.1.4
Using httpclient 2.8.3
Using mini_mime 1.1.5 (was 1.1.2)
Using trailblazer-option 0.1.2
Using uber 0.1.0
Using retriable 3.1.2
Using webrick 1.8.1 (was 1.7.0)
Using google-cloud-errors 1.3.1 (was 1.2.0)
Using json 2.7.1 (was 2.6.1)
Using mini_magick 4.12.0 (was 4.11.0)
Using naturally 2.2.1
Using optparse 0.1.1
Using plist 3.7.1 (was 3.6.0)
Using rubyzip 2.3.2
Using security 0.1.3
Using nanaimo 0.3.0
Using unicode-display_width 2.5.0 (was 1.8.0)
Using tty-screen 0.8.2 (was 0.8.1)
Using aws-sigv4 1.8.0 (was 1.5.0)
Using addressable 2.8.6 (was 2.8.0)
Using tty-cursor 0.7.1
Using http-cookie 1.0.5 (was 1.0.4)
Using faraday-multipart 1.0.4 (was 1.0.3)
Using representable 3.2.0 (was 3.1.1)
Using terminal-table 3.0.2 (was 1.8.0)
Using CFPropertyList 3.0.6 (was 3.0.5)
Using tty-spinner 0.9.3
Using word_wrap 1.0.0
Using commander 4.6.0
Using rouge 2.0.7
Using xcodeproj 1.23.0 (was 1.21.0)
Using ox 2.14.17 (was 2.14.11)
Using terminal-notifier 2.0.0
Using simctl 1.6.10 (was 1.6.8)
Using faraday 1.10.3 (was 1.10.0)
Using xcpretty 0.3.0
Using fastlane-plugin-update_android_strings 0.1.0
Using faraday-cookie_jar 0.0.7
Using google-cloud-env 2.1.0 (was 1.6.0)
Using signet 0.18.0 (was 0.16.1)
Using faraday_middleware 1.2.0
Using xcpretty-travis-formatter 1.0.1
Using google-cloud-core 1.6.1 (was 1.6.0)
Using googleauth 1.9.1 (was 1.1.3)
Using google-apis-core 0.11.2 (was 0.4.2)
Using google-apis-storage_v1 0.29.0 (was 0.13.0)
Using google-apis-androidpublisher_v3 0.54.0 (was 0.20.0)
Using google-apis-playcustomapp_v1 0.13.0 (was 0.7.0)
Using google-apis-iamcredentials_v1 0.17.0 (was 0.10.0)
Using google-cloud-storage 1.45.0 (was 1.36.2)
Installing aws-partitions 1.875.0 (was 1.587.0)
Using aws-sdk-core 3.190.1 (was 3.130.2)
Using aws-sdk-kms 1.75.0 (was 1.56.0)
Using aws-sdk-s3 1.142.0 (was 1.114.0)
Using fastlane 2.217.0 (was 2.205.2)
Bundle updated!
[✔] 🚀 
+------------------------------------------------------------------------+
|                              Used plugins                              |
+-------------------------------------+---------+------------------------+
| Plugin                              | Version | Action                 |
+-------------------------------------+---------+------------------------+
| fastlane-plugin-update_android_str  | 0.1.0   | update_android_strings |
| ings                                |         |                        |
+-------------------------------------+---------+------------------------+

[06:41:33]: ------------------------------
[06:41:33]: --- Step: default_platform ---
[06:41:33]: ------------------------------
[06:41:33]: Driving the lane 'android assemble' 🚀
[06:41:33]: ------------------------------------
[06:41:33]: --- Step: update_android_strings ---
[06:41:33]: ------------------------------------
+-------------------------------------+
|            Lane Context             |
+------------------+------------------+
| DEFAULT_PLATFORM | android          |
| PLATFORM_NAME    | android          |
| LANE_NAME        | android assemble |
+------------------+------------------+
[06:41:33]: the argument to replace_text() must be a String

+---------------------------------------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 💥   | update_android_strings | 0           |
+------+------------------------+-------------+

[06:41:33]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  fastlane finished with errors
    https://github.com/fastlane/fastlane/issues/21756 [open] 0 💬
    14 hours ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
        32: from /Users/ds/.rvm/gems/ruby-2.7.5/bin/ruby_executable_hooks:22:in `<main>'
        31: from /Users/ds/.rvm/gems/ruby-2.7.5/bin/ruby_executable_hooks:22:in `eval'
        30: from /Users/ds/.rvm/gems/ruby-2.7.5/bin/fastlane:23:in `<main>'
        29: from /Users/ds/.rvm/gems/ruby-2.7.5/bin/fastlane:23:in `load'
        28: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/bin/fastlane:23:in `<top (required)>'
        27: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        26: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        25: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        24: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        23: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        22: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        21: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        20: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        19: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        18: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        17: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        16: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        15: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        14: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        13: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/lane.rb:41:in `call'
        12: from Fastfile:22:in `block (2 levels) in parsing_binding'
        11: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        10: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
         9: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
         8: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
         7: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
         6: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
         5: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
         4: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-plugin-update_android_strings-0.1.0/lib/fastlane/plugin/update_android_strings/actions/update_android_strings_action.rb:36:in `run'
         3: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-plugin-update_android_strings-0.1.0/lib/fastlane/plugin/update_android_strings/helper/update_android_strings_helper.rb:11:in `updateXml'
         2: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-plugin-update_android_strings-0.1.0/lib/fastlane/plugin/update_android_strings/helper/update_android_strings_helper.rb:11:in `each'
         1: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-plugin-update_android_strings-0.1.0/lib/fastlane/plugin/update_android_strings/helper/update_android_strings_helper.rb:13:in `block in updateXml'
/Users/ds/.rvm/gems/ruby-2.7.5/gems/ox-2.14.17/lib/ox/element.rb:101:in `replace_text': \e[31m[!] the argument to replace_text() must be a String\e[0m (RuntimeError)
···
配置环境都是根据文档来的，结果出现一个 String 的错误。

**Comment by zhiqingchen** [comment]
这个命令是给 ci 用的，缺少环境变量则无法打包如：APP_NAME
建议使用 GitHub 进行打包，参考：
https://github.com/NervJS/taro-native-shell/actions

**Comment by zhiqingchen** [comment]
https://docs.taro.zone/docs/react-native#%E6%89%93%E5%8C%85%E5%8F%91%E5%B8%83%E5%AE%89%E5%8D%93%E5%8C%85

**Comment by Dssssds** [comment]
你好，感谢回复，我这边就是用 github 打包的，只是现在本地检测的那一步就无法通过。在第四部就卡死了。
![image](https://github.com/NervJS/taro-native-shell/assets/17268259/3847dd6f-7253-4d70-b964-7c849bf3a46f)

**Comment by Dssssds** [comment]
感谢了，我这边就是根据这两个文档来的。我描述一下，我的步骤。
1. 我把壳的 Git，fork 到了自己的工程下。
2. 将项目的安卓数据，同步到了 壳的项目内容。
3. 在本地执行了 （bundle update && bundle exec fastlane assemble ）
结果就在这里出问题了。
`+--------------------------------------+
|             Lane Context             |
+-------------------+------------------+
| DEFAULT_PLATFORM  | android          |
| PLATFORM_NAME     | android          |
| LANE_NAME         | android assemble |
| GRADLE_BUILD_TYPE | release          |
+-------------------+------------------+
[10:49:26]: Exit status of command '/Users/ds/Documents/Code/taro-project/alipay/Taro-RN-shell/android/gradlew assemblerelease -p . -Papp_id=com.tarodemo -Pandroid.injected.version.code=10 -Pandroid.injected.version.name=1.0.0 -Pandroid.injected.signing.store.file=/Users/ds/Documents/Code/taro-project/alipay/taroshell/android/app/debug.keystore -Pandroid.injected.signing.store.password=android -Pandroid.injected.signing.key.alias=androiddebugkey -Pandroid.injected.signing.key.password=android' was 1 instead of 0.

> Task :react-native-gradle-plugin:compileKotlin
w: /Users/ds/Documents/Code/taro-project/alipay/Taro-RN-shell/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (10, 37): 'BaseVariant' is deprecated. Deprecated in Java
w: /Users/ds/Documents/Code/taro-project/alipay/Taro-RN-shell/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (119, 30): 'BaseVariant' is deprecated. Deprecated in Java
w: /Users/ds/Documents/Code/taro-project/alipay/Taro-RN-shell/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (135, 26): 'BaseVariant' is deprecated. Deprecated in Java
w: /Users/ds/Documents/Code/taro-project/alipay/Taro-RN-shell/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (157, 32): 'BaseVariant' is deprecated. Deprecated in Java
w: /Users/ds/Documents/Code/taro-project/alipay/Taro-RN-shell/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (163, 31): 'BaseVariant' is deprecated. Deprecated in Java
w: /Users/ds/Documents/Code/taro-project/alipay/Taro-RN-shell/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (171, 36): 'BaseVariant' is deprecated. Deprecated in Java
w: /Users/ds/Documents/Code/taro-project/alipay/Taro-RN-shell/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactPlugin.kt: (114, 48): 'reactRoot: DirectoryProperty' is deprecated. reactRoot was confusing and has been replace with root to point to your root project and reactNativeDir to point to the folder of the react-native NPM package
w: /Users/ds/Documents/Code/taro-project/alipay/Taro-RN-shell/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (10, 37): 'ApplicationVariant' is deprecated. Deprecated in Java
w: /Users/ds/Documents/Code/taro-project/alipay/Taro-RN-shell/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (11, 37): 'BaseVariant' is deprecated. Deprecated in Java
w: /Users/ds/Documents/Code/taro-project/alipay/Taro-RN-shell/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (12, 37): 'LibraryVariant' is deprecated. Deprecated in Java
w: /Users/ds/Documents/Code/taro-project/alipay/Taro-RN-shell/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (27, 51): 'BaseVariant' is deprecated. Deprecated in Java
w: /Users/ds/Documents/Code/taro-project/alipay/Taro-RN-shell/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (130, 12): 'ApplicationVariant' is deprecated. Deprecated in Java
w: /Users/ds/Documents/Code/taro-project/alipay/Taro-RN-shell/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (131, 12): 'LibraryVariant' is deprecated. Deprecated in Java
w: /Users/ds/Documents/Code/taro-project/alipay/Taro-RN-shell/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (251, 14): 'BaseVariant' is deprecated. Deprecated in Java

> Task :react-native-gradle-plugin:compileJava NO-SOURCE
> Task :react-native-gradle-plugin:pluginDescriptors
> Task :react-native-gradle-plugin:processResources
> Task :react-native-gradle-plugin:classes
> Task :react-native-gradle-plugin:inspectClassesForKotlinIC
> Task :react-native-gradle-plugin:jar

> Configure project :expo-application
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-av
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Script '/Users/ds/Documents/Code/taro-project/alipay/Taro-RN-shell/node_modules/expo-modules-autolinking/scripts/android/autolinking_implementation.gradle' line: 272

* What went wrong:
A problem occurred evaluating project ':expo'.
> A problem occurred configuring project ':expo-barcode-scanner'.
   > Could not open proj generic class cache for build file '/Users/ds/Documents/Code/taro-project/alipay/Taro-RN-shell/node_modules/expo-barcode-scanner/android/build.gradle' (/Users/ds/.gradle/caches/7.5.1/scripts/8j8zquvx1m8909ev2oi79v1cf).
      > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':expo'.
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 9s
5 actionable tasks: 5 executed`

**Comment by zhiqingchen** [comment]
去掉这一步：将项目的安卓数据，同步到了 壳的项目内容。
看是否可以正常编译。

**Comment by Dssssds** [comment]
万分感谢！！！！可以了！！！
文档的描述我觉得可以改一改，容易被误导。
直接把 项目的安卓数据， 同步到， 壳的项目，在通过 github  进行打包就可以了。
感谢感谢。

**Comment by Dssssds** [comment]
这个 issues 可以关闭了，谢谢了。
