### ISSUE TITLE
救救孩子~为什么打包release.apk 生成的是官方的demo?

### ISSUE THREAD

**Issue by Ccc437647** [NervJS/taro-native-shell#95]
请问各位大佬们 我这个是 taro开发的rn项目
使用android studio 打包安卓apk文件
打包debug.apk 是我开发的项目工程文件 这个没问题
但是打包出来的release.apk 是框架的demo文件(App.js) 救救了 这个咋整

![18](https://github.com/NervJS/taro-native-shell/assets/74176833/51936d4f-99c6-4ee0-9214-a9f55e777f93)
![19](https://github.com/NervJS/taro-native-shell/assets/74176833/73cee23b-27af-4015-9e16-2a0f76b935cc)

**Comment by zhiqingchen** [comment]
版本？

**Comment by zhiqingchen** [comment]
https://stackoverflow.com/questions/76224572/how-to-skip-bundling-during-react-native-android-build
